---
- name: Preparing Workstation
  hosts: all
  tasks:

    # https://docs.ansible.com/ansible/2.9/modules/stat_module.html#stat-module
    - name: Check if file myfile exists
      stat:
        path: /tmp/myfile.txt
      register: myfile

    - name: touch myfile
      command: "touch /tmp/myfile.txt"
      when: not myfile.stat.exists

    # https://docs.ansible.com/ansible/2.9/modules/dnf_module.html#dnf-module
    # - name: update all packages (like dnf update command)
    #   become: true
    #   dnf:
    #     name: "*"
    #     state: latest

    # - name: install the latest version of Apache and MariaDB
    #   become: true
    #   dnf:
    #     name:
    #       - httpd
    #       - mariadb-server
    #     state: latest

    - name: install vim
      become: true
      dnf:
        name:
          - vim
        state: present
