---
- name: Preparing Workstation
  hosts: localhost # // TODO: para o teste com molecule precisava ser "all"
  connection: local
  gather_facts: yes # default=yes
  tasks:

    - name: Executar tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop:
        - tasks/00100-basic-setup.yml
        - tasks/00200-install-zsh.yml
        - tasks/00300-install-asdf.yml
