---
- name: Preparing Workstation
  hosts: localhost # // TODO: pra o teste com molecule precisava ser all
  connection: local
  tasks:

    # https://docs.ansible.com/ansible/2.9/modules/dnf_module.html#dnf-module
    - name: Update all packages (like dnf update command)
      become: true
      ansible.builtin.dnf:
        name: '*'
        state: latest # noqa: package-latest (para o lint não reclamar e não deve mesmo nesse caso)
        update_cache: yes
