---
- name: Preparing Workstation
  hosts: localhost # // TODO: para o teste com molecule precisava ser "all"
  connection: local
  tasks:

    # https://docs.ansible.com/ansible/2.9/modules/dnf_module.html#dnf-module
    - name: Update all packages (like dnf update command)
      become: true
      ansible.builtin.dnf:
        name: '*'
        state: latest # noqa: package-latest (https://ansible-lint.readthedocs.io/usage/#muting-warnings-to-avoid-false-positives)
        update_cache: yes

    - name: Install python3-ansible-lint
      become: true
      ansible.builtin.dnf:
        name:
          - python3-ansible-lint
        state: present
