---
- name: Preparing Workstation
  hosts: localhost # // TODO: para o teste com molecule precisava ser "all"
  connection: local
  gather_facts: yes # default=yes
  diff: true
  vars_files: vars.yml
  # vars_prompt:
  #   - name: dropbox_password
  #     prompt: "Qual é a senha da conta do Dropbox? (deixe vazio e enter se não vai precisar da senha)"
  #     private: yes # The user input is hidden by default but it can be made visible by setting private: no
  #     unsafe: yes # If you need to put in special characters (i.e {%) that might create templating errors, use the unsafe option
  tasks:

    - name: Executar tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop:
        # - tasks/00100-basic-setup.yml
        # - tasks/00200-install-zsh.yml
        # - tasks/00225-path.yml
        # - tasks/00250-install-oh-my-zsh.yml
        # - tasks/00275-install-zsh-powerlevel10k.yml
        # - tasks/00285-install-oh-my-zsh-plugins.yml
        # - tasks/00300-install-asdf.yml
        # - tasks/00400-add-vpn-sefin.yml
        # - tasks/00500-install-dropbox-v2.yml
        - tasks/00600-gnome-conf.yml

    # # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts['user_id']
    #     # msg: "Usuário: {{ ansible_user_id }}"
