###########################################################################
#### Setup do PATH
###########################################################################

- name: Prepara o arquivo ~/.zshrc para conter uma linha que comece com 'export PATH='
  block:
    - name: Verificar se a linha já existe
      ansible.builtin.shell: "grep '^export PATH=' ~/.zshrc || true"
      register: path_line
      changed_when: false

    - name: Adicionar linha 'export PATH="$PATH"' se não existir
      ansible.builtin.lineinfile:
        backup: yes
        path: ~/.zshrc
        insertafter: EOF
        line: 'export PATH="$PATH"'
      when: path_line.stdout == ""

- name: Adicionar diretório ~/.local/bin à variável PATH
  ansible.builtin.include_role:
    name: update-path
  vars:
    new_path: '{{ ansible_user_dir }}/.local/bin'
