###########################################################################
#### Setup do PATH
###########################################################################

# // TODO: Fiz essa pergunta ao chatgpt e parece que a resposta dele foi boa:
# "Crie pra mim uma role que vai receber um path e vai atualizar a
# variável PATH definida no ~/.zshrc. Não deve permitir itens duplicados."
# Com a role é possível fazer reuso e assim poder adicionar algo no PATH
# a partir de qualquer task
- name: Adicionar diretório ~/.local/bin à variável PATH
  ansible.builtin.lineinfile:
    backup: yes
    path: ~/.zshrc
    line: 'export PATH="$PATH:{{ ansible_user_dir }}/.local/bin"'
    state: present
    regexp: '^export PATH='
