###########################################################################
#### Instalar plugins do Oh-My-Zsh - https://github.com/ohmyzsh/ohmyzsh
###########################################################################

# // TODO; daquiiiiiiiiiiiiiii
