###########################################################################
#### Instalar Dropbox
###########################################################################

- name: Adicionar repositório do Dropbox
  ansible.builtin.yum_repository:
    name: Dropbox
    description: Dropbox Repository
    baseurl: http://linux.dropbox.com/fedora/$releasever/
    gpgkey: https://linux.dropbox.com/fedora/rpm-public-key.asc
    enabled: yes
    state: present
  become: true

- name: Install nautilus-dropbox
  ansible.builtin.dnf:
    name:
      - nautilus-dropbox
    state: present
    # // TODO: descomentar
    # update_cache: yes
  become: true

- name: Iniciar Dropbox
  ansible.builtin.command: dropbox start
  changed_when: false # // TODO: ver se tem como definir
  register: dropbox_start_output

- name: Debug - Inicialização do Dropbox
  ansible.builtin.debug:
    var: dropbox_start_output.stdout

- name: The Dropbox daemon is not installed
  when: "'The Dropbox daemon is not installed' in dropbox_start_output.stdout"
  block:

    - name: Instalar o daemon do Dropbox
      ansible.builtin.shell: echo y | dropbox start --install
      register: dropbox_install_output
      changed_when: dropbox_install_output.stdout_lines[-1] == "Done!"

    - name: Debug - Instalação o daemon do Dropbox
      ansible.builtin.debug:
        var: dropbox_install_output.stdout_lines

- name: Checar status
  ansible.builtin.command: dropbox status
  changed_when: false
  register: dropbox_status_output

- name: Debug - Checagem do status
  ansible.builtin.debug:
    var: dropbox_status_output.stdout

- name: Logar no Dropbox pois não está logado
  when: "'To link this computer to a Dropbox account, visit the following url:' in dropbox_status_output.stdout"
  block:

    - name: Obter URL de Login do Dropbox
      ansible.builtin.set_fact:
        url_login: "{{ dropbox_status_output.stdout_lines[-1] }}"

    - name: Debug - URL de Login do Dropbox
      ansible.builtin.debug:
        var: url_login

    - name: Informe a senha do Dropbox para o usuário {{ vars_username }}
      ansible.builtin.pause:
        prompt: "Senha"
        echo: no
      register: password_result

    # // TODO: remover
    # - name: Instalar virtualenv e setuptools (com pip)
    #   ansible.builtin.pip:
    #     name:
    #       - setuptools
    #     state: present

    - name: Criação do ambiente virtual
      ansible.builtin.shell: |
        virtualenv .venv
      changed_when: false # // TODO: melhorar?
      args:
        chdir: dropbox_login

    - name: Instalação das dependências
      ansible.builtin.pip:
        requirements: dropbox_login/requirements.txt
        virtualenv: dropbox_login/.venv
        chdir: "."

    - name: Executa o script python para logar no dropbox
      ansible.builtin.script:
        cmd: dropbox_login/dropbox_login.py --url "{{ url_login }}" --username "{{ vars_username }}" --password "{{ password_result.user_input }}"
      args:
        executable: dropbox_login/.venv/bin/python3

# TODO: daquiiiii: após o login o dropbox já vai começar a sincronizar todo o drive em algum lugar do disco

# ------------------

# sudo timeshift --list | grep -i -e NAME -e Dropbox
# sudo timeshift --restore --snapshot "2023-03-20_21-52-24"
# sudo timeshift --restore
