###########################################################################
#### Instalar Dropbox
###########################################################################

# cat <<EOF | sudo tee /etc/yum.repos.d/dropbox.repo
# [Dropbox]
# name=Dropbox Repository
# baseurl=http://linux.dropbox.com/fedora/\$releasever/
# gpgkey=https://linux.dropbox.com/fedora/rpm-public-key.asc
# enabled=1
# EOF

# dnf config-manager --set-disabled Dropbox
# sudo dnf config-manager --set-enabled Dropbox
# sudo rpm --import https://linux.dropbox.com/fedora/rpm-public-key.asc
# sudo dnf install nautilus-dropbox
# echo y | dropbox start --install

# sudo timeshift --list | grep -i -e NAME -e Dropbox
# sudo timeshift --restore --snapshot "2023-03-20_21-52-24"
# sudo timeshift --restore
