---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: fedora:36
    # image: myfedora:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
